apiVersion: v1
kind: ConfigMap
metadata:
  name: "vault-role-kubviz"
data:
  roleName: vault-role-kubviz
  policyNames: {{ .Values.vault.policyNames | quote }}
  servieAccounts: {{ include "client.serviceAccountName" . }}
  servieAccountNameSpaces: {{ .Release.Namespace }}
 