{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "client.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass | default "" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}