package gitea

import "time"

type PushEventPayload struct {
	Ref        string `json:"ref"`
	Before     string `json:"before"`
	After      string `json:"after"`
	CompareUrl string `json:"compare_url"`
	Commits    []struct {
		Id      string `json:"id"`
		Message string `json:"message"`
		Url     string `json:"url"`
		Author  struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"author"`
		Committer struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"committer"`
		Verification bool      `json:"verification"`
		Timestamp    time.Time `json:"timestamp"`
		Added        []string  `json:"added"`
		Removed      []string  `json:"removed"`
		Modified     []string  `json:"modified"`
	} `json:"commits"`
	HeadCommit struct {
		Id      string `json:"id"`
		Message string `json:"message"`
		Url     string `json:"url"`
		Author  struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"author"`
		Committer struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"committer"`
		Verification string    `json:"verification"`
		Timestamp    time.Time `json:"timestamp"`
		Added        []string  `json:"added"`
		Removed      []string  `json:"removed"`
		Modified     []string  `json:"modified"`
	} `json:"head_commit"`
	Repository struct {
		Id    int `json:"id"`
		Owner struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"owner"`
		Name            string    `json:"name"`
		FullName        string    `json:"full_name"`
		Description     string    `json:"description"`
		Empty           bool      `json:"empty"`
		Private         bool      `json:"private"`
		Fork            bool      `json:"fork"`
		Template        bool      `json:"template"`
		Parent          bool      `json:"parent"`
		Mirror          bool      `json:"mirror"`
		Size            int       `json:"size"`
		Language        string    `json:"language"`
		LanguagesUrl    string    `json:"languages_url"`
		HtmlUrl         string    `json:"html_url"`
		SshUrl          string    `json:"ssh_url"`
		CloneUrl        string    `json:"clone_url"`
		OriginalUrl     string    `json:"original_url"`
		Website         string    `json:"website"`
		StarsCount      int       `json:"stars_count"`
		ForksCount      int       `json:"forks_count"`
		WatchersCount   int       `json:"watchers_count"`
		OpenIssuesCount int       `json:"open_issues_count"`
		OpenPrCounter   int       `json:"open_pr_counter"`
		ReleaseCounter  int       `json:"release_counter"`
		DefaultBranch   string    `json:"default_branch"`
		Archived        bool      `json:"archived"`
		CreatedAt       time.Time `json:"created_at"`
		UpdatedAt       time.Time `json:"updated_at"`
		Permissions     struct {
			Admin bool `json:"admin"`
			Push  bool `json:"push"`
			Pull  bool `json:"pull"`
		} `json:"permissions"`
		HasIssues       bool `json:"has_issues"`
		InternalTracker struct {
			EnableTimeTracker                bool `json:"enable_time_tracker"`
			AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
			EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
		} `json:"internal_tracker"`
		HasWiki                   bool      `json:"has_wiki"`
		HasPullRequests           bool      `json:"has_pull_requests"`
		HasProjects               bool      `json:"has_projects"`
		IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
		AllowMergeCommits         bool      `json:"allow_merge_commits"`
		AllowRebase               bool      `json:"allow_rebase"`
		AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
		AllowSquashMerge          bool      `json:"allow_squash_merge"`
		DefaultMergeStyle         string    `json:"default_merge_style"`
		AvatarUrl                 string    `json:"avatar_url"`
		Internal                  bool      `json:"internal"`
		MirrorInterval            string    `json:"mirror_interval"`
		MirrorUpdated             time.Time `json:"mirror_updated"`
		RepoTransfer              bool      `json:"repo_transfer"`
	} `json:"repository"`
	Pusher struct {
		Id                int       `json:"id"`
		Login             string    `json:"login"`
		FullName          string    `json:"full_name"`
		Email             string    `json:"email"`
		AvatarUrl         string    `json:"avatar_url"`
		Language          string    `json:"language"`
		IsAdmin           bool      `json:"is_admin"`
		LastLogin         time.Time `json:"last_login"`
		Created           time.Time `json:"created"`
		Restricted        bool      `json:"restricted"`
		Active            bool      `json:"active"`
		ProhibitLogin     bool      `json:"prohibit_login"`
		Location          string    `json:"location"`
		Website           string    `json:"website"`
		Description       string    `json:"description"`
		Visibility        string    `json:"visibility"`
		FollowersCount    int       `json:"followers_count"`
		FollowingCount    int       `json:"following_count"`
		StarredReposCount int       `json:"starred_repos_count"`
		Username          string    `json:"username"`
	} `json:"pusher"`
	Sender struct {
		Id                int       `json:"id"`
		Login             string    `json:"login"`
		FullName          string    `json:"full_name"`
		Email             string    `json:"email"`
		AvatarUrl         string    `json:"avatar_url"`
		Language          string    `json:"language"`
		IsAdmin           bool      `json:"is_admin"`
		LastLogin         time.Time `json:"last_login"`
		Created           time.Time `json:"created"`
		Restricted        bool      `json:"restricted"`
		Active            bool      `json:"active"`
		ProhibitLogin     bool      `json:"prohibit_login"`
		Location          string    `json:"location"`
		Website           string    `json:"website"`
		Description       string    `json:"description"`
		Visibility        string    `json:"visibility"`
		FollowersCount    int       `json:"followers_count"`
		FollowingCount    int       `json:"following_count"`
		StarredReposCount int       `json:"starred_repos_count"`
		Username          string    `json:"username"`
	} `json:"sender"`
}

type ForkEventPayload struct {
	Forkee struct {
		Id    int `json:"id"`
		Owner struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"owner"`
		Name            string    `json:"name"`
		FullName        string    `json:"full_name"`
		Description     string    `json:"description"`
		Empty           bool      `json:"empty"`
		Private         bool      `json:"private"`
		Fork            bool      `json:"fork"`
		Template        bool      `json:"template"`
		Parent          bool      `json:"parent"`
		Mirror          bool      `json:"mirror"`
		Size            int       `json:"size"`
		Language        string    `json:"language"`
		LanguagesUrl    string    `json:"languages_url"`
		HtmlUrl         string    `json:"html_url"`
		SshUrl          string    `json:"ssh_url"`
		CloneUrl        string    `json:"clone_url"`
		OriginalUrl     string    `json:"original_url"`
		Website         string    `json:"website"`
		StarsCount      int       `json:"stars_count"`
		ForksCount      int       `json:"forks_count"`
		WatchersCount   int       `json:"watchers_count"`
		OpenIssuesCount int       `json:"open_issues_count"`
		OpenPrCounter   int       `json:"open_pr_counter"`
		ReleaseCounter  int       `json:"release_counter"`
		DefaultBranch   string    `json:"default_branch"`
		Archived        bool      `json:"archived"`
		CreatedAt       time.Time `json:"created_at"`
		UpdatedAt       time.Time `json:"updated_at"`
		Permissions     struct {
			Admin bool `json:"admin"`
			Push  bool `json:"push"`
			Pull  bool `json:"pull"`
		} `json:"permissions"`
		HasIssues       bool `json:"has_issues"`
		InternalTracker struct {
			EnableTimeTracker                bool `json:"enable_time_tracker"`
			AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
			EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
		} `json:"internal_tracker"`
		HasWiki                   bool      `json:"has_wiki"`
		HasPullRequests           bool      `json:"has_pull_requests"`
		HasProjects               bool      `json:"has_projects"`
		IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
		AllowMergeCommits         bool      `json:"allow_merge_commits"`
		AllowRebase               bool      `json:"allow_rebase"`
		AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
		AllowSquashMerge          bool      `json:"allow_squash_merge"`
		DefaultMergeStyle         string    `json:"default_merge_style"`
		AvatarUrl                 string    `json:"avatar_url"`
		Internal                  bool      `json:"internal"`
		MirrorInterval            string    `json:"mirror_interval"`
		MirrorUpdated             time.Time `json:"mirror_updated"`
		RepoTransfer              bool      `json:"repo_transfer"`
	} `json:"forkee"`
	Repository struct {
		Id    int `json:"id"`
		Owner struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"owner"`
		Name        string `json:"name"`
		FullName    string `json:"full_name"`
		Description string `json:"description"`
		Empty       bool   `json:"empty"`
		Private     bool   `json:"private"`
		Fork        bool   `json:"fork"`
		Template    bool   `json:"template"`
		Parent      struct {
			Id    int `json:"id"`
			Owner struct {
				Id                int       `json:"id"`
				Login             string    `json:"login"`
				FullName          string    `json:"full_name"`
				Email             string    `json:"email"`
				AvatarUrl         string    `json:"avatar_url"`
				Language          string    `json:"language"`
				IsAdmin           bool      `json:"is_admin"`
				LastLogin         time.Time `json:"last_login"`
				Created           time.Time `json:"created"`
				Restricted        bool      `json:"restricted"`
				Active            bool      `json:"active"`
				ProhibitLogin     bool      `json:"prohibit_login"`
				Location          string    `json:"location"`
				Website           string    `json:"website"`
				Description       string    `json:"description"`
				Visibility        string    `json:"visibility"`
				FollowersCount    int       `json:"followers_count"`
				FollowingCount    int       `json:"following_count"`
				StarredReposCount int       `json:"starred_repos_count"`
				Username          string    `json:"username"`
			} `json:"owner"`
			Name            string    `json:"name"`
			FullName        string    `json:"full_name"`
			Description     string    `json:"description"`
			Empty           bool      `json:"empty"`
			Private         bool      `json:"private"`
			Fork            bool      `json:"fork"`
			Template        bool      `json:"template"`
			Parent          bool      `json:"parent"`
			Mirror          bool      `json:"mirror"`
			Size            int       `json:"size"`
			Language        string    `json:"language"`
			LanguagesUrl    string    `json:"languages_url"`
			HtmlUrl         string    `json:"html_url"`
			SshUrl          string    `json:"ssh_url"`
			CloneUrl        string    `json:"clone_url"`
			OriginalUrl     string    `json:"original_url"`
			Website         string    `json:"website"`
			StarsCount      int       `json:"stars_count"`
			ForksCount      int       `json:"forks_count"`
			WatchersCount   int       `json:"watchers_count"`
			OpenIssuesCount int       `json:"open_issues_count"`
			OpenPrCounter   int       `json:"open_pr_counter"`
			ReleaseCounter  int       `json:"release_counter"`
			DefaultBranch   string    `json:"default_branch"`
			Archived        bool      `json:"archived"`
			CreatedAt       time.Time `json:"created_at"`
			UpdatedAt       time.Time `json:"updated_at"`
			Permissions     struct {
				Admin bool `json:"admin"`
				Push  bool `json:"push"`
				Pull  bool `json:"pull"`
			} `json:"permissions"`
			HasIssues       bool `json:"has_issues"`
			InternalTracker struct {
				EnableTimeTracker                bool `json:"enable_time_tracker"`
				AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
				EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
			} `json:"internal_tracker"`
			HasWiki                   bool      `json:"has_wiki"`
			HasPullRequests           bool      `json:"has_pull_requests"`
			HasProjects               bool      `json:"has_projects"`
			IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
			AllowMergeCommits         bool      `json:"allow_merge_commits"`
			AllowRebase               bool      `json:"allow_rebase"`
			AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
			AllowSquashMerge          bool      `json:"allow_squash_merge"`
			DefaultMergeStyle         string    `json:"default_merge_style"`
			AvatarUrl                 string    `json:"avatar_url"`
			Internal                  bool      `json:"internal"`
			MirrorInterval            string    `json:"mirror_interval"`
			MirrorUpdated             time.Time `json:"mirror_updated"`
			RepoTransfer              bool      `json:"repo_transfer"`
		} `json:"parent"`
		Mirror          bool      `json:"mirror"`
		Size            int       `json:"size"`
		Language        string    `json:"language"`
		LanguagesUrl    string    `json:"languages_url"`
		HtmlUrl         string    `json:"html_url"`
		SshUrl          string    `json:"ssh_url"`
		CloneUrl        string    `json:"clone_url"`
		OriginalUrl     string    `json:"original_url"`
		Website         string    `json:"website"`
		StarsCount      int       `json:"stars_count"`
		ForksCount      int       `json:"forks_count"`
		WatchersCount   int       `json:"watchers_count"`
		OpenIssuesCount int       `json:"open_issues_count"`
		OpenPrCounter   int       `json:"open_pr_counter"`
		ReleaseCounter  int       `json:"release_counter"`
		DefaultBranch   string    `json:"default_branch"`
		Archived        bool      `json:"archived"`
		CreatedAt       time.Time `json:"created_at"`
		UpdatedAt       time.Time `json:"updated_at"`
		Permissions     struct {
			Admin bool `json:"admin"`
			Push  bool `json:"push"`
			Pull  bool `json:"pull"`
		} `json:"permissions"`
		HasIssues       bool `json:"has_issues"`
		InternalTracker struct {
			EnableTimeTracker                bool `json:"enable_time_tracker"`
			AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
			EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
		} `json:"internal_tracker"`
		HasWiki                   bool      `json:"has_wiki"`
		HasPullRequests           bool      `json:"has_pull_requests"`
		HasProjects               bool      `json:"has_projects"`
		IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
		AllowMergeCommits         bool      `json:"allow_merge_commits"`
		AllowRebase               bool      `json:"allow_rebase"`
		AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
		AllowSquashMerge          bool      `json:"allow_squash_merge"`
		DefaultMergeStyle         string    `json:"default_merge_style"`
		AvatarUrl                 string    `json:"avatar_url"`
		Internal                  bool      `json:"internal"`
		MirrorInterval            string    `json:"mirror_interval"`
		MirrorUpdated             time.Time `json:"mirror_updated"`
		RepoTransfer              bool      `json:"repo_transfer"`
	} `json:"repository"`
	Sender struct {
		Id                int       `json:"id"`
		Login             string    `json:"login"`
		FullName          string    `json:"full_name"`
		Email             string    `json:"email"`
		AvatarUrl         string    `json:"avatar_url"`
		Language          string    `json:"language"`
		IsAdmin           bool      `json:"is_admin"`
		LastLogin         time.Time `json:"last_login"`
		Created           time.Time `json:"created"`
		Restricted        bool      `json:"restricted"`
		Active            bool      `json:"active"`
		ProhibitLogin     bool      `json:"prohibit_login"`
		Location          string    `json:"location"`
		Website           string    `json:"website"`
		Description       string    `json:"description"`
		Visibility        string    `json:"visibility"`
		FollowersCount    int       `json:"followers_count"`
		FollowingCount    int       `json:"following_count"`
		StarredReposCount int       `json:"starred_repos_count"`
		Username          string    `json:"username"`
	} `json:"sender"`
}

type PullRequestPayload struct {
	Action      string `json:"action"`
	Number      int    `json:"number"`
	PullRequest struct {
		Id     int    `json:"id"`
		Url    string `json:"url"`
		Number int    `json:"number"`
		User   struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"user"`
		Title               string   `json:"title"`
		Body                string   `json:"body"`
		Labels              []string `json:"labels"`
		Milestone           string   `json:"milestone"`
		Assignee            string   `json:"assignee"`
		Assignees           string   `json:"assignees"`
		State               string   `json:"state"`
		IsLocked            bool     `json:"is_locked"`
		Comments            int      `json:"comments"`
		HtmlUrl             string   `json:"html_url"`
		DiffUrl             string   `json:"diff_url"`
		PatchUrl            string   `json:"patch_url"`
		Mergeable           bool     `json:"mergeable"`
		Merged              bool     `json:"merged"`
		MergedAt            string   `json:"merged_at"`
		MergeCommitSha      string   `json:"merge_commit_sha"`
		MergedBy            string   `json:"merged_by"`
		AllowMaintainerEdit bool     `json:"allow_maintainer_edit"`
		Base                struct {
			Label  string `json:"label"`
			Ref    string `json:"ref"`
			Sha    string `json:"sha"`
			RepoId int    `json:"repo_id"`
			Repo   struct {
				Id    int `json:"id"`
				Owner struct {
					Id                int       `json:"id"`
					Login             string    `json:"login"`
					FullName          string    `json:"full_name"`
					Email             string    `json:"email"`
					AvatarUrl         string    `json:"avatar_url"`
					Language          string    `json:"language"`
					IsAdmin           bool      `json:"is_admin"`
					LastLogin         time.Time `json:"last_login"`
					Created           time.Time `json:"created"`
					Restricted        bool      `json:"restricted"`
					Active            bool      `json:"active"`
					ProhibitLogin     bool      `json:"prohibit_login"`
					Location          string    `json:"location"`
					Website           string    `json:"website"`
					Description       string    `json:"description"`
					Visibility        string    `json:"visibility"`
					FollowersCount    int       `json:"followers_count"`
					FollowingCount    int       `json:"following_count"`
					StarredReposCount int       `json:"starred_repos_count"`
					Username          string    `json:"username"`
				} `json:"owner"`
				Name            string    `json:"name"`
				FullName        string    `json:"full_name"`
				Description     string    `json:"description"`
				Empty           bool      `json:"empty"`
				Private         bool      `json:"private"`
				Fork            bool      `json:"fork"`
				Template        bool      `json:"template"`
				Parent          bool      `json:"parent"`
				Mirror          bool      `json:"mirror"`
				Size            int       `json:"size"`
				Language        string    `json:"language"`
				LanguagesUrl    string    `json:"languages_url"`
				HtmlUrl         string    `json:"html_url"`
				SshUrl          string    `json:"ssh_url"`
				CloneUrl        string    `json:"clone_url"`
				OriginalUrl     string    `json:"original_url"`
				Website         string    `json:"website"`
				StarsCount      int       `json:"stars_count"`
				ForksCount      int       `json:"forks_count"`
				WatchersCount   int       `json:"watchers_count"`
				OpenIssuesCount int       `json:"open_issues_count"`
				OpenPrCounter   int       `json:"open_pr_counter"`
				ReleaseCounter  int       `json:"release_counter"`
				DefaultBranch   string    `json:"default_branch"`
				Archived        bool      `json:"archived"`
				CreatedAt       time.Time `json:"created_at"`
				UpdatedAt       time.Time `json:"updated_at"`
				Permissions     struct {
					Admin bool `json:"admin"`
					Push  bool `json:"push"`
					Pull  bool `json:"pull"`
				} `json:"permissions"`
				HasIssues       bool `json:"has_issues"`
				InternalTracker struct {
					EnableTimeTracker                bool `json:"enable_time_tracker"`
					AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
					EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
				} `json:"internal_tracker"`
				HasWiki                   bool      `json:"has_wiki"`
				HasPullRequests           bool      `json:"has_pull_requests"`
				HasProjects               bool      `json:"has_projects"`
				IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
				AllowMergeCommits         bool      `json:"allow_merge_commits"`
				AllowRebase               bool      `json:"allow_rebase"`
				AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
				AllowSquashMerge          bool      `json:"allow_squash_merge"`
				DefaultMergeStyle         string    `json:"default_merge_style"`
				AvatarUrl                 string    `json:"avatar_url"`
				Internal                  bool      `json:"internal"`
				MirrorInterval            string    `json:"mirror_interval"`
				MirrorUpdated             time.Time `json:"mirror_updated"`
				RepoTransfer              bool      `json:"repo_transfer"`
			} `json:"repo"`
		} `json:"base"`
		Head struct {
			Label  string `json:"label"`
			Ref    string `json:"ref"`
			Sha    string `json:"sha"`
			RepoId int    `json:"repo_id"`
			Repo   struct {
				Id    int `json:"id"`
				Owner struct {
					Id                int       `json:"id"`
					Login             string    `json:"login"`
					FullName          string    `json:"full_name"`
					Email             string    `json:"email"`
					AvatarUrl         string    `json:"avatar_url"`
					Language          string    `json:"language"`
					IsAdmin           bool      `json:"is_admin"`
					LastLogin         time.Time `json:"last_login"`
					Created           time.Time `json:"created"`
					Restricted        bool      `json:"restricted"`
					Active            bool      `json:"active"`
					ProhibitLogin     bool      `json:"prohibit_login"`
					Location          string    `json:"location"`
					Website           string    `json:"website"`
					Description       string    `json:"description"`
					Visibility        string    `json:"visibility"`
					FollowersCount    int       `json:"followers_count"`
					FollowingCount    int       `json:"following_count"`
					StarredReposCount int       `json:"starred_repos_count"`
					Username          string    `json:"username"`
				} `json:"owner"`
				Name        string `json:"name"`
				FullName    string `json:"full_name"`
				Description string `json:"description"`
				Empty       bool   `json:"empty"`
				Private     bool   `json:"private"`
				Fork        bool   `json:"fork"`
				Template    bool   `json:"template"`
				Parent      struct {
					Id    int `json:"id"`
					Owner struct {
						Id                int       `json:"id"`
						Login             string    `json:"login"`
						FullName          string    `json:"full_name"`
						Email             string    `json:"email"`
						AvatarUrl         string    `json:"avatar_url"`
						Language          string    `json:"language"`
						IsAdmin           bool      `json:"is_admin"`
						LastLogin         time.Time `json:"last_login"`
						Created           time.Time `json:"created"`
						Restricted        bool      `json:"restricted"`
						Active            bool      `json:"active"`
						ProhibitLogin     bool      `json:"prohibit_login"`
						Location          string    `json:"location"`
						Website           string    `json:"website"`
						Description       string    `json:"description"`
						Visibility        string    `json:"visibility"`
						FollowersCount    int       `json:"followers_count"`
						FollowingCount    int       `json:"following_count"`
						StarredReposCount int       `json:"starred_repos_count"`
						Username          string    `json:"username"`
					} `json:"owner"`
					Name            string    `json:"name"`
					FullName        string    `json:"full_name"`
					Description     string    `json:"description"`
					Empty           bool      `json:"empty"`
					Private         bool      `json:"private"`
					Fork            bool      `json:"fork"`
					Template        bool      `json:"template"`
					Parent          bool      `json:"parent"`
					Mirror          bool      `json:"mirror"`
					Size            int       `json:"size"`
					Language        string    `json:"language"`
					LanguagesUrl    string    `json:"languages_url"`
					HtmlUrl         string    `json:"html_url"`
					SshUrl          string    `json:"ssh_url"`
					CloneUrl        string    `json:"clone_url"`
					OriginalUrl     string    `json:"original_url"`
					Website         string    `json:"website"`
					StarsCount      int       `json:"stars_count"`
					ForksCount      int       `json:"forks_count"`
					WatchersCount   int       `json:"watchers_count"`
					OpenIssuesCount int       `json:"open_issues_count"`
					OpenPrCounter   int       `json:"open_pr_counter"`
					ReleaseCounter  int       `json:"release_counter"`
					DefaultBranch   string    `json:"default_branch"`
					Archived        bool      `json:"archived"`
					CreatedAt       time.Time `json:"created_at"`
					UpdatedAt       time.Time `json:"updated_at"`
					Permissions     struct {
						Admin bool `json:"admin"`
						Push  bool `json:"push"`
						Pull  bool `json:"pull"`
					} `json:"permissions"`
					HasIssues       bool `json:"has_issues"`
					InternalTracker struct {
						EnableTimeTracker                bool `json:"enable_time_tracker"`
						AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
						EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
					} `json:"internal_tracker"`
					HasWiki                   bool      `json:"has_wiki"`
					HasPullRequests           bool      `json:"has_pull_requests"`
					HasProjects               bool      `json:"has_projects"`
					IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
					AllowMergeCommits         bool      `json:"allow_merge_commits"`
					AllowRebase               bool      `json:"allow_rebase"`
					AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
					AllowSquashMerge          bool      `json:"allow_squash_merge"`
					DefaultMergeStyle         string    `json:"default_merge_style"`
					AvatarUrl                 string    `json:"avatar_url"`
					Internal                  bool      `json:"internal"`
					MirrorInterval            string    `json:"mirror_interval"`
					MirrorUpdated             time.Time `json:"mirror_updated"`
					RepoTransfer              bool      `json:"repo_transfer"`
				} `json:"parent"`
				Mirror          bool      `json:"mirror"`
				Size            int       `json:"size"`
				Language        string    `json:"language"`
				LanguagesUrl    string    `json:"languages_url"`
				HtmlUrl         string    `json:"html_url"`
				SshUrl          string    `json:"ssh_url"`
				CloneUrl        string    `json:"clone_url"`
				OriginalUrl     string    `json:"original_url"`
				Website         string    `json:"website"`
				StarsCount      int       `json:"stars_count"`
				ForksCount      int       `json:"forks_count"`
				WatchersCount   int       `json:"watchers_count"`
				OpenIssuesCount int       `json:"open_issues_count"`
				OpenPrCounter   int       `json:"open_pr_counter"`
				ReleaseCounter  int       `json:"release_counter"`
				DefaultBranch   string    `json:"default_branch"`
				Archived        bool      `json:"archived"`
				CreatedAt       time.Time `json:"created_at"`
				UpdatedAt       time.Time `json:"updated_at"`
				Permissions     struct {
					Admin bool `json:"admin"`
					Push  bool `json:"push"`
					Pull  bool `json:"pull"`
				} `json:"permissions"`
				HasIssues       bool `json:"has_issues"`
				InternalTracker struct {
					EnableTimeTracker                bool `json:"enable_time_tracker"`
					AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
					EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
				} `json:"internal_tracker"`
				HasWiki                   bool      `json:"has_wiki"`
				HasPullRequests           bool      `json:"has_pull_requests"`
				HasProjects               bool      `json:"has_projects"`
				IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
				AllowMergeCommits         bool      `json:"allow_merge_commits"`
				AllowRebase               bool      `json:"allow_rebase"`
				AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
				AllowSquashMerge          bool      `json:"allow_squash_merge"`
				DefaultMergeStyle         string    `json:"default_merge_style"`
				AvatarUrl                 string    `json:"avatar_url"`
				Internal                  bool      `json:"internal"`
				MirrorInterval            string    `json:"mirror_interval"`
				MirrorUpdated             time.Time `json:"mirror_updated"`
				RepoTransfer              bool      `json:"repo_transfer"`
			} `json:"repo"`
		} `json:"head"`
		MergeBase string    `json:"merge_base"`
		DueDate   time.Time `json:"due_date"`
		CreatedAt time.Time `json:"created_at"`
		UpdatedAt time.Time `json:"updated_at"`
		ClosedAt  time.Time `json:"closed_at"`
	} `json:"pull_request"`
	Repository struct {
		Id    int `json:"id"`
		Owner struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"owner"`
		Name            string    `json:"name"`
		FullName        string    `json:"full_name"`
		Description     string    `json:"description"`
		Empty           bool      `json:"empty"`
		Private         bool      `json:"private"`
		Fork            bool      `json:"fork"`
		Template        bool      `json:"template"`
		Parent          bool      `json:"parent"`
		Mirror          bool      `json:"mirror"`
		Size            int       `json:"size"`
		Language        string    `json:"language"`
		LanguagesUrl    string    `json:"languages_url"`
		HtmlUrl         string    `json:"html_url"`
		SshUrl          string    `json:"ssh_url"`
		CloneUrl        string    `json:"clone_url"`
		OriginalUrl     string    `json:"original_url"`
		Website         string    `json:"website"`
		StarsCount      int       `json:"stars_count"`
		ForksCount      int       `json:"forks_count"`
		WatchersCount   int       `json:"watchers_count"`
		OpenIssuesCount int       `json:"open_issues_count"`
		OpenPrCounter   int       `json:"open_pr_counter"`
		ReleaseCounter  int       `json:"release_counter"`
		DefaultBranch   string    `json:"default_branch"`
		Archived        bool      `json:"archived"`
		CreatedAt       time.Time `json:"created_at"`
		UpdatedAt       time.Time `json:"updated_at"`
		Permissions     struct {
			Admin bool `json:"admin"`
			Push  bool `json:"push"`
			Pull  bool `json:"pull"`
		} `json:"permissions"`
		HasIssues       bool `json:"has_issues"`
		InternalTracker struct {
			EnableTimeTracker                bool `json:"enable_time_tracker"`
			AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
			EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
		} `json:"internal_tracker"`
		HasWiki                   bool      `json:"has_wiki"`
		HasPullRequests           bool      `json:"has_pull_requests"`
		HasProjects               bool      `json:"has_projects"`
		IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
		AllowMergeCommits         bool      `json:"allow_merge_commits"`
		AllowRebase               bool      `json:"allow_rebase"`
		AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
		AllowSquashMerge          bool      `json:"allow_squash_merge"`
		DefaultMergeStyle         string    `json:"default_merge_style"`
		AvatarUrl                 string    `json:"avatar_url"`
		Internal                  bool      `json:"internal"`
		MirrorInterval            string    `json:"mirror_interval"`
		MirrorUpdated             time.Time `json:"mirror_updated"`
		RepoTransfer              bool      `json:"repo_transfer"`
	} `json:"repository"`
	Sender struct {
		Id                int       `json:"id"`
		Login             string    `json:"login"`
		FullName          string    `json:"full_name"`
		Email             string    `json:"email"`
		AvatarUrl         string    `json:"avatar_url"`
		Language          string    `json:"language"`
		IsAdmin           bool      `json:"is_admin"`
		LastLogin         time.Time `json:"last_login"`
		Created           time.Time `json:"created"`
		Restricted        bool      `json:"restricted"`
		Active            bool      `json:"active"`
		ProhibitLogin     bool      `json:"prohibit_login"`
		Location          string    `json:"location"`
		Website           string    `json:"website"`
		Description       string    `json:"description"`
		Visibility        string    `json:"visibility"`
		FollowersCount    int       `json:"followers_count"`
		FollowingCount    int       `json:"following_count"`
		StarredReposCount int       `json:"starred_repos_count"`
		Username          string    `json:"username"`
	} `json:"sender"`
	Review interface{} `json:"review"`
}

type PullRequestCommentedPayload struct {
	Action string `json:"action"`
	Issue  struct {
		Id      int    `json:"id"`
		Url     string `json:"url"`
		HtmlUrl string `json:"html_url"`
		Number  int    `json:"number"`
		User    struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"user"`
		OriginalAuthor   string    `json:"original_author"`
		OriginalAuthorId int       `json:"original_author_id"`
		Title            string    `json:"title"`
		Body             string    `json:"body"`
		Ref              string    `json:"ref"`
		Labels           []string  `json:"labels"`
		Milestone        string    `json:"milestone"`
		Assignee         string    `json:"assignee"`
		Assignees        string    `json:"assignees"`
		State            string    `json:"state"`
		IsLocked         bool      `json:"is_locked"`
		Comments         int       `json:"comments"`
		CreatedAt        time.Time `json:"created_at"`
		UpdatedAt        time.Time `json:"updated_at"`
		ClosedAt         time.Time `json:"closed_at"`
		DueDate          time.Time `json:"due_date"`
		PullRequest      struct {
			Merged   bool      `json:"merged"`
			MergedAt time.Time `json:"merged_at"`
		} `json:"pull_request"`
		Repository struct {
			Id       int    `json:"id"`
			Name     string `json:"name"`
			Owner    string `json:"owner"`
			FullName string `json:"full_name"`
		} `json:"repository"`
	} `json:"issue"`
	Comment struct {
		Id             int    `json:"id"`
		HtmlUrl        string `json:"html_url"`
		PullRequestUrl string `json:"pull_request_url"`
		IssueUrl       string `json:"issue_url"`
		User           struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"user"`
		OriginalAuthor   string    `json:"original_author"`
		OriginalAuthorId int       `json:"original_author_id"`
		Body             string    `json:"body"`
		CreatedAt        time.Time `json:"created_at"`
		UpdatedAt        time.Time `json:"updated_at"`
	} `json:"comment"`
	Repository struct {
		Id    int `json:"id"`
		Owner struct {
			Id                int       `json:"id"`
			Login             string    `json:"login"`
			FullName          string    `json:"full_name"`
			Email             string    `json:"email"`
			AvatarUrl         string    `json:"avatar_url"`
			Language          string    `json:"language"`
			IsAdmin           bool      `json:"is_admin"`
			LastLogin         time.Time `json:"last_login"`
			Created           time.Time `json:"created"`
			Restricted        bool      `json:"restricted"`
			Active            bool      `json:"active"`
			ProhibitLogin     bool      `json:"prohibit_login"`
			Location          string    `json:"location"`
			Website           string    `json:"website"`
			Description       string    `json:"description"`
			Visibility        string    `json:"visibility"`
			FollowersCount    int       `json:"followers_count"`
			FollowingCount    int       `json:"following_count"`
			StarredReposCount int       `json:"starred_repos_count"`
			Username          string    `json:"username"`
		} `json:"owner"`
		Name            string    `json:"name"`
		FullName        string    `json:"full_name"`
		Description     string    `json:"description"`
		Empty           bool      `json:"empty"`
		Private         bool      `json:"private"`
		Fork            bool      `json:"fork"`
		Template        bool      `json:"template"`
		Parent          bool      `json:"parent"`
		Mirror          bool      `json:"mirror"`
		Size            int       `json:"size"`
		Language        string    `json:"language"`
		LanguagesUrl    string    `json:"languages_url"`
		HtmlUrl         string    `json:"html_url"`
		SshUrl          string    `json:"ssh_url"`
		CloneUrl        string    `json:"clone_url"`
		OriginalUrl     string    `json:"original_url"`
		Website         string    `json:"website"`
		StarsCount      int       `json:"stars_count"`
		ForksCount      int       `json:"forks_count"`
		WatchersCount   int       `json:"watchers_count"`
		OpenIssuesCount int       `json:"open_issues_count"`
		OpenPrCounter   int       `json:"open_pr_counter"`
		ReleaseCounter  int       `json:"release_counter"`
		DefaultBranch   string    `json:"default_branch"`
		Archived        bool      `json:"archived"`
		CreatedAt       time.Time `json:"created_at"`
		UpdatedAt       time.Time `json:"updated_at"`
		Permissions     struct {
			Admin bool `json:"admin"`
			Push  bool `json:"push"`
			Pull  bool `json:"pull"`
		} `json:"permissions"`
		HasIssues       bool `json:"has_issues"`
		InternalTracker struct {
			EnableTimeTracker                bool `json:"enable_time_tracker"`
			AllowOnlyContributorsToTrackTime bool `json:"allow_only_contributors_to_track_time"`
			EnableIssueDependencies          bool `json:"enable_issue_dependencies"`
		} `json:"internal_tracker"`
		HasWiki                   bool      `json:"has_wiki"`
		HasPullRequests           bool      `json:"has_pull_requests"`
		HasProjects               bool      `json:"has_projects"`
		IgnoreWhitespaceConflicts bool      `json:"ignore_whitespace_conflicts"`
		AllowMergeCommits         bool      `json:"allow_merge_commits"`
		AllowRebase               bool      `json:"allow_rebase"`
		AllowRebaseExplicit       bool      `json:"allow_rebase_explicit"`
		AllowSquashMerge          bool      `json:"allow_squash_merge"`
		DefaultMergeStyle         string    `json:"default_merge_style"`
		AvatarUrl                 string    `json:"avatar_url"`
		Internal                  bool      `json:"internal"`
		MirrorInterval            string    `json:"mirror_interval"`
		MirrorUpdated             time.Time `json:"mirror_updated"`
		RepoTransfer              bool      `json:"repo_transfer"`
	} `json:"repository"`
	Sender struct {
		Id                int       `json:"id"`
		Login             string    `json:"login"`
		FullName          string    `json:"full_name"`
		Email             string    `json:"email"`
		AvatarUrl         string    `json:"avatar_url"`
		Language          string    `json:"language"`
		IsAdmin           bool      `json:"is_admin"`
		LastLogin         time.Time `json:"last_login"`
		Created           time.Time `json:"created"`
		Restricted        bool      `json:"restricted"`
		Active            bool      `json:"active"`
		ProhibitLogin     bool      `json:"prohibit_login"`
		Location          string    `json:"location"`
		Website           string    `json:"website"`
		Description       string    `json:"description"`
		Visibility        string    `json:"visibility"`
		FollowersCount    int       `json:"followers_count"`
		FollowingCount    int       `json:"following_count"`
		StarredReposCount int       `json:"starred_repos_count"`
		Username          string    `json:"username"`
	} `json:"sender"`
	IsPull bool `json:"is_pull"`
}
