package model

//"github.com/aquasecurity/trivy/pkg/sbom/cyclonedx"

// type Sbom struct {
// 	ID     string
// 	Report cyclonedx.BOM
// }

// type SbomData struct {
// 	ID               string
// 	ClusterName string
// 	ComponentName    string
// 	PackageName string
// 	PackageUrl       string
// 	BomRef           string
// 	SerialNumber     string
// 	CycloneDxVersion int
// 	BomFormat        string
// }

type Sbom struct {
	ID          string
	ClusterName string
	Report      map[string]interface{}
}

// type SbomData struct {
// 	ID               string
// 	ClusterName      string
// 	ComponentName    string
// 	PackageName      string
// 	PackageUrl       string
// 	BomRef           string
// 	SerialNumber     string
// 	CycloneDxVersion int
// 	BomFormat        string
// }

// type AutoGenerated struct {
// 	Schema       string `json:"$schema"`
// 	BomFormat    string `json:"bomFormat"`
// 	SpecVersion  string `json:"specVersion"`
// 	SerialNumber string `json:"serialNumber"`
// 	Version      int    `json:"version"`
// 	Metadata     struct {
// 		Timestamp time.Time `json:"timestamp"`
// 		Tools     []struct {
// 			Vendor  string `json:"vendor"`
// 			Name    string `json:"name"`
// 			Version string `json:"version"`
// 		} `json:"tools"`
// 		Component struct {
// 			BomRef     string `json:"bom-ref"`
// 			Type       string `json:"type"`
// 			Name       string `json:"name"`
// 			Purl       string `json:"purl"`
// 			Properties []struct {
// 				Name  string `json:"name"`
// 				Value string `json:"value"`
// 			} `json:"properties"`
// 		} `json:"component"`
// 	} `json:"metadata"`
// 	Components []struct {
// 		BomRef     string `json:"bom-ref"`
// 		Type       string `json:"type"`
// 		Name       string `json:"name"`
// 		Properties []struct {
// 			Name  string `json:"name"`
// 			Value string `json:"value"`
// 		} `json:"properties"`
// 		Version string `json:"version,omitempty"`
// 		Purl    string `json:"purl,omitempty"`
// 	} `json:"components"`
// 	Dependencies []struct {
// 		Ref       string   `json:"ref"`
// 		DependsOn []string `json:"dependsOn"`
// 	} `json:"dependencies"`
// 	Vulnerabilities []interface{} `json:"vulnerabilities"`
// }

// type AutoGenerated struct {
// 	Schema       string `json:"$schema"`
// 	BomFormat    string `json:"bomFormat"`
// 	SpecVersion  string `json:"specVersion"`
// 	SerialNumber string `json:"serialNumber"`
// 	Version      int    `json:"version"`
// 	Metadata     struct {
// 		Timestamp time.Time `json:"timestamp"`
// 		Tools     []struct {
// 			Vendor  string `json:"vendor"`
// 			Name    string `json:"name"`
// 			Version string `json:"version"`
// 		} `json:"tools"`
// 		Component struct {
// 			BomRef     string `json:"bom-ref"`
// 			Type       string `json:"type"`
// 			Name       string `json:"name"`
// 			Purl       string `json:"purl"`
// 			Properties []struct {
// 				Name  string `json:"name"`
// 				Value string `json:"value"`
// 			} `json:"properties"`
// 		} `json:"component"`
// 	} `json:"metadata"`
// 	Components []struct {
// 		BomRef     string `json:"bom-ref"`
// 		Type       string `json:"type"`
// 		Name       string `json:"name"`
// 		Version    string `json:"version,omitempty"`
// 		Properties []struct {
// 			Name  string `json:"name"`
// 			Value string `json:"value"`
// 		} `json:"properties"`
// 		Supplier struct {
// 			Name string `json:"name"`
// 		} `json:"supplier,omitempty"`
// 		Hashes []struct {
// 			Alg     string `json:"alg"`
// 			Content string `json:"content"`
// 		} `json:"hashes,omitempty"`
// 		Licenses []struct {
// 			Expression string `json:"expression"`
// 		} `json:"licenses,omitempty"`
// 		Purl string `json:"purl,omitempty"`
// 	} `json:"components"`
// 	Dependencies []struct {
// 		Ref       string   `json:"ref"`
// 		DependsOn []string `json:"dependsOn"`
// 	} `json:"dependencies"`
// 	Vulnerabilities []interface{} `json:"vulnerabilities"`
// }

// type spdxAutoGenerated struct {
// 	SpdxVersion       string `json:"spdxVersion"`
// 	DataLicense       string `json:"dataLicense"`
// 	SPDXID            string `json:"SPDXID"`
// 	Name              string `json:"name"`
// 	DocumentNamespace string `json:"documentNamespace"`
// 	CreationInfo      struct {
// 		LicenseListVersion string    `json:"licenseListVersion"`
// 		Creators           []string  `json:"creators"`
// 		Created            time.Time `json:"created"`
// 	} `json:"creationInfo"`
// 	Packages []struct {
// 		Name             string `json:"name"`
// 		SPDXID           string `json:"SPDXID"`
// 		VersionInfo      string `json:"versionInfo,omitempty"`
// 		Supplier         string `json:"supplier,omitempty"`
// 		DownloadLocation string `json:"downloadLocation"`
// 		LicenseConcluded string `json:"licenseConcluded,omitempty"`
// 		LicenseDeclared  string `json:"licenseDeclared,omitempty"`
// 		CopyrightText    string `json:"copyrightText"`
// 		ExternalRefs     []struct {
// 			ReferenceCategory string `json:"referenceCategory"`
// 			ReferenceType     string `json:"referenceType"`
// 			ReferenceLocator  string `json:"referenceLocator"`
// 		} `json:"externalRefs,omitempty"`
// 		AttributionTexts      []string `json:"attributionTexts,omitempty"`
// 		PrimaryPackagePurpose string   `json:"primaryPackagePurpose"`
// 		SourceInfo            string   `json:"sourceInfo,omitempty"`
// 	} `json:"packages"`
// 	Relationships []struct {
// 		SpdxElementID      string `json:"spdxElementId"`
// 		RelatedSpdxElement string `json:"relatedSpdxElement"`
// 		RelationshipType   string `json:"relationshipType"`
// 	} `json:"relationships"`
// }
