package model

import "time"

//"github.com/aquasecurity/trivy/pkg/sbom/cyclonedx"

// type Sbom struct {
// 	ID     string
// 	Report cyclonedx.BOM
// }

// type SbomData struct {
// 	ID               string
// 	ClusterName string
// 	ComponentName    string
// 	PackageName string
// 	PackageUrl       string
// 	BomRef           string
// 	SerialNumber     string
// 	CycloneDxVersion int
// 	BomFormat        string
// }

type Cyclonedx struct {
	ID string
	ClusterName string
	SbomData SbomAutoGenerated
}

type SbomAutoGenerated struct {
	Schema       string `json:"$schema"`
	BomFormat    string `json:"bomFormat"`
	SpecVersion  string `json:"specVersion"`
	SerialNumber string `json:"serialNumber"`
	Version      int    `json:"version"`
	Metadata     struct {
		Timestamp time.Time `json:"timestamp"`
		Tools     []struct {
			Vendor  string `json:"vendor"`
			Name    string `json:"name"`
			Version string `json:"version"`
		} `json:"tools"`
		Component struct {
			BomRef     string `json:"bom-ref"`
			Type       string `json:"type"`
			Name       string `json:"name"`
			Purl       string `json:"purl"`
			Properties []struct {
				Name  string `json:"name"`
				Value string `json:"value"`
			} `json:"properties"`
		} `json:"component"`
	} `json:"metadata"`
	Components []struct {
		BomRef     string `json:"bom-ref"`
		Type       string `json:"type"`
		Name       string `json:"name"`
		Properties []struct {
			Name  string `json:"name"`
			Value string `json:"value"`
		} `json:"properties"`
		Version string `json:"version,omitempty"`
		Purl    string `json:"purl,omitempty"`
	} `json:"components"`
	Dependencies []struct {
		Ref       string   `json:"ref"`
		DependsOn []string `json:"dependsOn"`
	} `json:"dependencies"`
	Vulnerabilities []interface{} `json:"vulnerabilities"`
}


