package constants

const (
	KUBESCORE_SUBJECT            = "METRICS.kubescore"
	TRIVY_K8S_SUBJECT            = "METRICS.trivyk8s"
	StreamSubjects               = "METRICS.*"
	EventSubject                 = "METRICS.kubvizevent"
	StreamName                   = "METRICS"
	EventSubject_getall_resource = "METRICS.ketall"
	EventSubject_outdated_images = "METRICS.outdated"
	EventSubject_rakees          = "METRICS.rakees"
	EventSubject_deleted         = "METRICS.deletedAPI"
	EventSubject_depricated      = "METRICS.deprecatedAPI"
	KetallSubject                = "METRICS.ketall"
	KetallConsumer               = "KETALL_EVENTS_CONSUMER"
	RakeesSubject                = "METRICS.rakees"
	RakeesConsumer               = "RAKEES_METRICS_CONSUMER"
	OutdatedSubject              = "METRICS.outdated"
	OutdatedConsumer             = "OUTDATED_EVENTS_CONSUMER"
	DeprecatedSubject            = "METRICS.deprecatedAPI"
	DeprecatedConsumer           = "DEPRECATED_API_CONSUMER"
	DeletedSubject               = "METRICS.deletedAPI"
	DeletedConsumer              = "DELETED_API_CONSUMER"
	KubvizSubject                = "METRICS.kubvizevent"
	KubvizConsumer               = "KUBVIZ_EVENTS_CONSUMER"
	KubscoreConsumer             = "KUBSCORE_CONSUMER"
	TrivyConsumer                = "TRIVY_CONSUMER"
	TRIVY_IMAGE_SUBJECT          = "METRICS.trivyimage"
	Trivy_Image_Consumer         = "TRIVY_IMAGE_CONSUMER"
)
