// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type KubeScore struct {
	ID          string `json:"id"`
	ClusterName string `json:"clusterName"`
	ObjectName  string `json:"objectName"`
	Kind        string `json:"kind"`
	APIVersion  string `json:"apiVersion"`
	Name        string `json:"name"`
	Namespace   string `json:"namespace"`
	TargetType  string `json:"targetType"`
	Description string `json:"description"`
	Path        string `json:"path"`
	Summary     string `json:"summary"`
	FileName    string `json:"fileName"`
	FileRow     int    `json:"fileRow"`
	EventTime   string `json:"eventTime"`
}

type NamespaceData struct {
	Namespace      string           `json:"namespace"`
	OutdatedImages []*OutdatedImage `json:"outdatedImages"`
	KubeScores     []*KubeScore     `json:"kubeScores"`
	Resources      []*Resource      `json:"resources"`
}

type OutdatedImage struct {
	ClusterName    string `json:"clusterName"`
	Namespace      string `json:"namespace"`
	Pod            string `json:"pod"`
	CurrentImage   string `json:"currentImage"`
	CurrentTag     string `json:"currentTag"`
	LatestVersion  string `json:"latestVersion"`
	VersionsBehind int    `json:"versionsBehind"`
	EventTime      string `json:"eventTime"`
}

type Query struct {
}

type Resource struct {
	ClusterName string `json:"clusterName"`
	Namespace   string `json:"namespace"`
	Kind        string `json:"kind"`
	Resource    string `json:"resource"`
	Age         string `json:"age"`
	EventTime   string `json:"eventTime"`
}
