{
 "title": "Azure",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventType",
    "query": "SELECT EventType FROM default.azure_devops"
   },
   {
    "name": "Author",
    "query": "SELECT Author FROM default.azure_devops"
   }
  ]
 },
 "panels": [
  {
   "title": "Azure Contributions",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"azure_devops\" \nWHERE $timeFilterByColumn(TimeStamp) AND EventType IN ($eventType) AND Author IN ($Author)\nGROUP BY EventType, Author, RepoName",
     "rawQuery": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"azure_devops\" \nWHERE TimeStamp >= toDateTime(1694534229) AND TimeStamp <= toDateTime(1694620629) AND EventType IN ('git.push') AND Author IN ('Anila Soman')\nGROUP BY EventType, Author, RepoName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Azure push events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Push_Events\nFROM default.azure_devops\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'git.push'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Push_Events\nFROM default.azure_devops\nWHERE TimeStamp >= toDateTime(1694534188) AND TimeStamp <= toDateTime(1694620588) AND EventType = 'git.push'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Azure Merge events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Merge_Events\nFROM default.azure_devops \nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'git.pullrequest.merged'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Merge_Events\nFROM default.azure_devops \nWHERE TimeStamp >= toDateTime(1694534208) AND TimeStamp <= toDateTime(1694620608) AND EventType = 'git.pullrequest.merged'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Azure Push event counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'git.push'",
     "rawQuery": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE TimeStamp >= toDateTime(1694534146) AND TimeStamp <= toDateTime(1694620546) AND EventType = 'git.push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Azure Merge events count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'git.pullrequest.merged'",
     "rawQuery": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE TimeStamp >= toDateTime(1694534169) AND TimeStamp <= toDateTime(1694620569) AND EventType = 'git.pullrequest.merged'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Azure Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.azure_devops\nWHERE $timeFilterByColumn(TimeStamp) AND EventType IN ($eventType) AND Author IN ($Author)",
     "rawQuery": "SELECT * FROM default.azure_devops\nWHERE TimeStamp >= toDateTime(1694534128) AND TimeStamp <= toDateTime(1694620528) AND EventType IN ('git.push') AND Author IN ('Anila Soman')",
     "round": "0s"
    }
   ]
  }
 ]
}