{
 "title": "BitBucket",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventType",
    "query": "SELECT EventType FROM default.bitbucket"
   },
   {
    "name": "Author",
    "query": "SELECT Author FROM default.bitbucket"
   }
  ]
 },
 "panels": [
  {
   "title": "BitBucket Events",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"bitbucket\" \nWHERE $timeFilterByColumn(TimeStamp) AND EventType In ($eventType) AND Author IN ($Author)\nGROUP BY EventType, Author, RepoName",
     "rawQuery": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"bitbucket\" \nWHERE TimeStamp >= toDateTime(1694536440) AND TimeStamp <= toDateTime(1694622840) AND EventType In ('repo:push','pullrequest:created','pullrequest:fulfilled') AND Author IN ('')\nGROUP BY EventType, Author, RepoName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of BitBucket Push events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Push_Events\nFROM default.bitbucket\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'repo:push'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Push_Events\nFROM default.bitbucket\nWHERE TimeStamp >= toDateTime(1694536383) AND TimeStamp <= toDateTime(1694622783) AND EventType = 'repo:push'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of BitBucket Merge events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Merge_Events\nFROM default.bitbucket\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'pullrequest:fulfilled'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Merge_Events\nFROM default.bitbucket\nWHERE TimeStamp >= toDateTime(1694536421) AND TimeStamp <= toDateTime(1694622821) AND EventType = 'pullrequest:fulfilled'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BitBucket Push Events Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'repo:push'",
     "rawQuery": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE TimeStamp >= toDateTime(1694536343) AND TimeStamp <= toDateTime(1694622743) AND EventType = 'repo:push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BitBucket Merge events count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'pullrequest:fulfilled'",
     "rawQuery": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE TimeStamp >= toDateTime(1694536364) AND TimeStamp <= toDateTime(1694622764) AND EventType = 'pullrequest:fulfilled'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BitBucket Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.bitbucket\nWHERE $timeFilterByColumn(TimeStamp) AND EventType IN ($eventType) AND Author In ($Author)",
     "rawQuery": "SELECT * FROM default.bitbucket\nWHERE TimeStamp >= toDateTime(1694536323) AND TimeStamp <= toDateTime(1694622723) AND EventType IN ('repo:push','pullrequest:created','pullrequest:fulfilled') AND Author In ('')",
     "round": "0s"
    }
   ]
  }
 ]
}