{
 "title": "Container-Bridge",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Quay Container Registry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.quaycontainerpush\nWHERE $timeFilterByColumn(EventTime)\nORDER BY EventTime",
     "rawQuery": "SELECT * FROM default.quaycontainerpush\nWHERE EventTime >= toDateTime(1694165676) AND EventTime <= toDateTime(1694252076)\nORDER BY EventTime",
     "round": "0s"
    }
   ]
  },
  {
   "title": "JFrog Container Registry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.jfrogcontainerpush\nWHERE $timeFilterByColumn(EventTime)\nORDER BY EventTime DESC",
     "rawQuery": "SELECT * FROM default.jfrogcontainerpush\nWHERE EventTime >= toDateTime(1694226084) AND EventTime <= toDateTime(1694247684)\nORDER BY EventTime DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Azure Container Registry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.azurecontainerpush\nWHERE $timeFilterByColumn(EventTime)\nORDER BY EventTime DESC",
     "rawQuery": "SELECT * FROM default.azurecontainerpush\nWHERE EventTime >= toDateTime(1694165623) AND EventTime <= toDateTime(1694252023)\nORDER BY EventTime DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "DockerHub",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.dockerhubbuild\nWHERE $timeFilterByColumn(EventTime)\nORDER BY EventTime DESC\n",
     "rawQuery": "SELECT * FROM default.dockerhubbuild\nWHERE EventTime >= toDateTime(1694165564) AND EventTime <= toDateTime(1694251964)\nORDER BY EventTime DESC",
     "round": "0s"
    }
   ]
  }
 ]
}