{
 "title": "kubedatas",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "SELECT namespace FROM default.events"
   },
   {
    "name": "reason",
    "query": "SELECT reason FROM default.events"
   },
   {
    "name": "kind",
    "query": "SELECT kind FROM default.events"
   },
   {
    "name": "host",
    "query": "SELECT host FROM default.events"
   }
  ]
 },
 "panels": [
  {
   "title": "healthy in Namespace : $namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count()\nFROM $table\nWHERE reason IN ('Healthy') AND namespace IN ($namespace)\n",
     "rawQuery": "SELECT\n    count()\nFROM default.events\nWHERE reason IN ('Healthy') AND namespace IN ('default','ingress-nginx','kube-system','monitoring')",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "unHealthy in Namespace: $namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count()\nFROM $table\nWHERE reason IN ('Unhealthy') AND namespace IN ($namespace)",
     "rawQuery": "SELECT\n    count()\nFROM default.events\nWHERE reason IN ('Unhealthy') AND namespace IN ('default','ingress-nginx','kube-system','monitoring')",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "kubernetes",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    *\r\n      \r\nFROM $table\r\n\r\nWHERE namespace IN ($namespace) AND reason IN ($reason) AND $timeFilter AND host IN ($host) AND kind IN ($kind)",
     "round": "0s",
     "table": "events"
    }
   ]
  }
 ]
}