{
 "title": "GitBridge",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GITHUB Push events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GitHub FROM default.github\nWHERE EventType = 'push'",
     "rawQuery": "SELECT count(*) AS GitHub FROM default.github\nWHERE EventType = 'push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GITLAB Push events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) Gitlab FROM default.gitlab\nWHERE EventType = 'Push Hook'",
     "rawQuery": "SELECT count(*) Gitlab FROM default.gitlab\nWHERE EventType = 'Push Hook'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BITBUCKET Push events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE EventType = 'repo:push'",
     "rawQuery": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE EventType = 'repo:push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GITEA Push events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GiTea FROM default.gitea\nWHERE EventType = 'push'",
     "rawQuery": "SELECT count(*) AS GiTea FROM default.gitea\nWHERE EventType = 'push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "AZURE Push events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE EventType = 'git.push'",
     "rawQuery": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE EventType = 'git.push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GITHUB Merge events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GitHub FROM default.github\nWHERE EventType = 'pull_request'",
     "rawQuery": "SELECT count(*) AS GitHub FROM default.github\nWHERE EventType = 'pull_request'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GITLAB Merge events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GitLab FROM default.gitlab\nWHERE EventType = 'Merge Request Hook'",
     "rawQuery": "SELECT count(*) AS GitLab FROM default.gitlab\nWHERE EventType = 'Merge Request Hook'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BITBUCKET Merge events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE EventType = 'pullrequest:fulfilled'",
     "rawQuery": "SELECT count(*) AS BitBucket FROM default.bitbucket\nWHERE EventType = 'pullrequest:fulfilled'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GITEA Merge events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS Gitea FROM default.gitea\nWHERE EventType = 'pull_request'",
     "rawQuery": "SELECT count(*) AS Gitea FROM default.gitea\nWHERE EventType = 'pull_request'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "AZURE Merge events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE EventType = 'git.pullrequest.merged'",
     "rawQuery": "SELECT count(*) AS Azure FROM default.azure_devops\nWHERE EventType = 'git.pullrequest.merged'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Azure Push Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of Push events on Azure by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Azure_Push_Events\nFROM default.azure_devops\nWHERE EventType = 'git.push'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Azure Merge Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of Merge events on Azure by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Azure_Merge_Events\nFROM default.azure_devops\nWHERE EventType = 'git.pullrequest.merged'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "BitBucket Push Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of Push events on BitBucket by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Push_Events\nFROM default.bitbucket\nWHERE EventType = 'repo:push'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "BitBucket Merge Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of Merge events on BitBucket by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Merge_Events\nFROM default.bitbucket\nWHERE EventType = 'pullrequest:fulfilled'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "GiTea Push Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of Push events on GiTea by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Push_Events\nFROM default.gitea\nWHERE EventType = 'push'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "GiTea Merge Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of Merge events on GiTea by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Merge_Events\nFROM default.gitea\nWHERE EventType = 'pull_request'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "GitLab Push Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of push events on GitLab by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Push_Events\nFROM default.gitlab\nWHERE EventType = 'Push Hook'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "GitLab Merge Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of merge events on GitLab by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Merge_Events\nFROM default.gitlab\nWHERE EventType = 'Merge Request Hook'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Github Push Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of push events on Github by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Push_Events\nFROM default.github\nWHERE EventType = 'push'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Github Merge Events by Author",
   "type": "barchart",
   "description": "The panel displays the count of merge events on Github by each author. It provides insights into the contribution activity of different authors within the specified repository.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Author, count(*) AS Merge_Events\nFROM default.github\nWHERE EventType = 'pull_request'\nGROUP BY Author",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Azure",
   "type": "table",
   "description": "This panel displays all the events occured in the Azure Procider",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT Author, CommitID, CommitUrl, EventType, RepoName, TimeStamp FROM default.\"azure_devops\" ORDER BY TimeStamp DESC",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "BitBucket",
   "type": "table",
   "description": "This panel displays all the events occured in the BitBucket Providers",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT Author, CommitID, CommitUrl, EventType, RepoName, TimeStamp FROM default.\"bitbucket\" ORDER BY TimeStamp DESC",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "GiTea",
   "type": "table",
   "description": "This panel displays all the events occured in the GiTea provider",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT Author, CommitID, CommitUrl, EventType, RepoName, TimeStamp FROM default.\"gitea\" ORDER BY TimeStamp DESC",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "GitLab",
   "type": "table",
   "description": "This panel displays all the events occured in the GitLab provider.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "rawSql": "SELECT Author, CommitID, CommitUrl, EventType, RepoName, TimeStamp FROM default.\"gitlab\" ORDER BY TimeStamp DESC",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "GitHub",
   "type": "table",
   "description": "This panel displays all the events occured in the GitHub provider.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "rawSql": "SELECT Author, CommitID, CommitUrl, EventType, RepoName, TimeStamp FROM default.\"github\" ORDER BY TimeStamp DESC",
     "selectedFormat": 1
    }
   ]
  }
 ]
}