{
 "title": "GiTea",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventType",
    "query": "SELECT EventType FROM  default.gitea"
   },
   {
    "name": "Author",
    "query": "SELECT Author FROM default.gitea"
   }
  ]
 },
 "panels": [
  {
   "title": "GiTea Contributions",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"gitea\" \nWHERE $timeFilterByColumn(TimeStamp) AND EventType IN ($eventType) AND Author IN ($Author)\nGROUP BY EventType, Author, RepoName",
     "rawQuery": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"gitea\" \nWHERE TimeStamp >= toDateTime(1694535218) AND TimeStamp <= toDateTime(1694621618) AND EventType IN ('push','pull_request') AND Author IN ('')\nGROUP BY EventType, Author, RepoName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Gitea push events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Push_Events\nFROM default.gitea\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'push'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Push_Events\nFROM default.gitea\nWHERE TimeStamp >= toDateTime(1694535157) AND TimeStamp <= toDateTime(1694621557) AND EventType = 'push'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Gitea Merge events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Merge_Events\nFROM default.gitea\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'pull_request'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Merge_Events\nFROM default.gitea\nWHERE TimeStamp >= toDateTime(1694535179) AND TimeStamp <= toDateTime(1694621579) AND EventType = 'pull_request'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BitBucket Push event count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GiTea FROM default.gitea\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'push'",
     "rawQuery": "SELECT count(*) AS GiTea FROM default.gitea\nWHERE TimeStamp >= toDateTime(1694535111) AND TimeStamp <= toDateTime(1694621511) AND EventType = 'push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BitBucket Merge events count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS Gitea FROM default.gitea\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'pull_request'",
     "rawQuery": "SELECT count(*) AS Gitea FROM default.gitea\nWHERE TimeStamp >= toDateTime(1694535137) AND TimeStamp <= toDateTime(1694621537) AND EventType = 'pull_request'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GiTea Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.gitea\nWHERE $timeFilterByColumn(TimeStamp) AND EventType IN ($eventType) AND Author IN ($Author)",
     "rawQuery": "SELECT * FROM default.gitea\nWHERE TimeStamp >= toDateTime(1694535089) AND TimeStamp <= toDateTime(1694621489) AND EventType IN ('push','pull_request') AND Author IN ('')",
     "round": "0s"
    }
   ]
  }
 ]
}