{
 "title": "GitHub",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Author",
    "query": "select Author from default.github"
   },
   {
    "name": "eventType",
    "query": "select EventType from default.github"
   }
  ]
 },
 "panels": [
  {
   "title": "GitHub Contributors",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"github\" \nWHERE $timeFilterByColumn(TimeStamp) AND Author IN ($Author) AND EventType IN ($eventType)\nGROUP BY EventType, Author, RepoName",
     "rawQuery": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"github\" \nWHERE TimeStamp >= toDateTime(1694597007) AND TimeStamp <= toDateTime(1694618607) AND Author IN ('ahinvinith') AND EventType IN ('push','pull_request')\nGROUP BY EventType, Author, RepoName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of GitHub push events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Push_Events\nFROM default.github\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'push'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Push_Events\nFROM default.github\nWHERE TimeStamp >= toDateTime(1694596958) AND TimeStamp <= toDateTime(1694618558) AND EventType = 'push'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of GitHub Merge events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Merge_Events\nFROM default.github\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'pull_request'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Merge_Events\nFROM default.github\nWHERE TimeStamp >= toDateTime(1694596980) AND TimeStamp <= toDateTime(1694618580) AND EventType = 'pull_request'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GitHub Merge event Count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GitHub FROM default.github\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'pull_request'",
     "rawQuery": "SELECT count(*) AS GitHub FROM default.github\nWHERE TimeStamp >= toDateTime(1694596901) AND TimeStamp <= toDateTime(1694618501) AND EventType = 'pull_request'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GitHub Push events count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GitHub FROM default.github\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'push'",
     "rawQuery": "SELECT count(*) AS GitHub FROM default.github\nWHERE TimeStamp >= toDateTime(1694596932) AND TimeStamp <= toDateTime(1694618532) AND EventType = 'push'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Github Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.github\nWHERE $timeFilterByColumn(TimeStamp) AND EventType IN ($eventType) AND Author IN ($Author)\nORDER BY TimeStamp DESC",
     "rawQuery": "SELECT * FROM default.github\nWHERE TimeStamp >= toDateTime(1694596869) AND TimeStamp <= toDateTime(1694618469) AND EventType IN ('push','pull_request') AND Author IN ('ahinvinith')\nORDER BY TimeStamp DESC",
     "round": "0s"
    }
   ]
  }
 ]
}