{
 "title": "GitLab",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventType",
    "query": "SELECT EventType FROM default.gitlab"
   },
   {
    "name": "Author",
    "query": "SELECT Author FROM default.gitlab"
   }
  ]
 },
 "panels": [
  {
   "title": "GitLab Contributions",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"gitlab\" \nWHERE $timeFilterByColumn(TimeStamp) AND EventType In ($eventType) AND Author IN ($Author)\nGROUP BY EventType, Author, RepoName",
     "rawQuery": "SELECT EventType, Author, RepoName , count(*) AS Total\nFROM \"default\".\"gitlab\" \nWHERE TimeStamp >= toDateTime(1694533326) AND TimeStamp <= toDateTime(1694619726) AND EventType In ('Push Hook') AND Author IN ('Ahin Vinith')\nGROUP BY EventType, Author, RepoName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of GitLab Push events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Push_Events\nFROM default.gitlab\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'Push Hook'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Push_Events\nFROM default.gitlab\nWHERE TimeStamp >= toDateTime(1694533277) AND TimeStamp <= toDateTime(1694619677) AND EventType = 'Push Hook'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of GitHub Merge events grouped by author",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Author, count(*) AS Merge_Events\nFROM default.gitlab\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'Merge Request Hook'\nGROUP BY Author",
     "rawQuery": "SELECT Author, count(*) AS Merge_Events\nFROM default.gitlab\nWHERE TimeStamp >= toDateTime(1694533298) AND TimeStamp <= toDateTime(1694619698) AND EventType = 'Merge Request Hook'\nGROUP BY Author",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GitLab Push Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) Gitlab FROM default.gitlab\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'Push Hook'",
     "rawQuery": "SELECT count(*) Gitlab FROM default.gitlab\nWHERE TimeStamp >= toDateTime(1694533230) AND TimeStamp <= toDateTime(1694619630) AND EventType = 'Push Hook'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GitLab Merge events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) AS GitLab FROM default.gitlab\nWHERE $timeFilterByColumn(TimeStamp) AND EventType = 'Merge Request Hook'",
     "rawQuery": "SELECT count(*) AS GitLab FROM default.gitlab\nWHERE TimeStamp >= toDateTime(1694533256) AND TimeStamp <= toDateTime(1694619656) AND EventType = 'Merge Request Hook'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "GitLab Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.gitlab\nWHERE $timeFilterByColumn(TimeStamp) AND EventType IN ($eventType) AND Author IN ($Author)",
     "rawQuery": "SELECT * FROM default.gitlab\nWHERE TimeStamp >= toDateTime(1694533200) AND TimeStamp <= toDateTime(1694619600) AND EventType IN ('Push Hook') AND Author IN ('Ahin Vinith')",
     "round": "0s"
    }
   ]
  }
 ]
}