{
 "title": "KuberHealth",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Running kuberhealthy checks",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT CheckName, count(OK) AS counts\nFROM default.kuberhealthy\nWHERE OK = '1'\nGROUP BY CheckName",
     "rawQuery": "SELECT CheckName, count(OK) AS counts\nFROM default.kuberhealthy\nWHERE OK = '1'\nGROUP BY CheckName",
     "round": "0s"
    }
   ]
  },
  {
   "title": " Faliure kuberhealthy checks",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT CheckName, count(OK) AS counts\nFROM default.kuberhealthy\nWHERE OK = '0'\nGROUP BY CheckName",
     "rawQuery": "SELECT CheckName, count(OK) AS counts\nFROM default.kuberhealthy\nWHERE OK = '0'\nGROUP BY CheckName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Kuberhealthy Pod Restarts Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "Select LastRun, OK,Errors\nfrom default.kuberhealthy\nwhere CheckName LIKE '%pod-restarts%' AND $__timeFilter(LastRun)"
    }
   ]
  },
  {
   "title": "Kuberhealthy Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "Select LastRun, OK\nfrom default.kuberhealthy\nwhere $__timeFilter(LastRun)"
    }
   ]
  },
  {
   "title": "Kuberhealthy  Counts Over Time.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "Select LastRun, count(*)\nfrom default.kuberhealthy\nwhere $__timeFilter(LastRun)\nGroup By LastRun"
    }
   ]
  },
  {
   "title": "Image Pull Check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "Select LastRun, OK,Errors\nfrom default.kuberhealthy\nwhere CheckName LIKE '%image-pull-check%' AND $__timeFilter(LastRun)"
    }
   ]
  },
  {
   "title": "Resource-quata check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "Select LastRun, OK,Errors\nfrom default.kuberhealthy\nwhere CheckName LIKE '%resource-quota%' AND $__timeFilter(LastRun)"
    }
   ]
  },
  {
   "title": "Kuberhealthy Errors Over Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "rawSql": "Select LastRun, OK,Errors\nfrom default.kuberhealthy\nwhere $__timeFilter(LastRun) AND OK='0'\nOrder BY LastRun DESC"
    }
   ]
  },
  {
   "title": "Kuberhealthy Tables",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"default\".\"kuberhealthy\"\nWhere $__timeFilter(LastRun)\nOrder By LastRun DESC \n\n"
    }
   ]
  },
  {
   "title": "Success Kuberhealthy Checks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT CheckName, count(OK) AS counts\nFROM default.kuberhealthy\nWHERE OK = '1'\nGROUP BY CheckName"
    }
   ]
  },
  {
   "title": "Faliure Kuberhealthy Checks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT CheckName, count(OK) AS counts\nFROM default.kuberhealthy\nWHERE OK = '0'\nGROUP BY CheckName"
    }
   ]
  },
  {
   "title": "Total count Kuberhealthy Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(OK)\nFROM default.kuberhealthy\nWHERE OK = '1'"
    }
   ]
  },
  {
   "title": "Total Count Kuberhealthy Faliures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(OK)\nFROM default.kuberhealthy\nWHERE OK = '0'"
    }
   ]
  }
 ]
}