{
 "title": "Kubviz Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Monitoring Clusters",
   "type": "table",
   "description": "This panel displays all the names of the cluster monitoring the kubernetes events and features",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT DISTINCT ClusterName FROM default.events",
     "rawQuery": "SELECT DISTINCT ClusterName FROM default.events",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Clusters with Most Activity",
   "type": "gauge",
   "description": "This panel displays the which cluster has the highest events.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName,count(*) AS Events From default.events\nWHERE $timeFilterByColumn(EventTime) \nGROUP BY ClusterName\nORDER BY Events DESC\nLIMIT 1",
     "rawQuery": "SELECT ClusterName,count(*) AS Events From default.events\nWHERE EventTime >= toDateTime(1693460315) AND EventTime <= toDateTime(1693460615) \nGROUP BY ClusterName\nORDER BY Events DESC\nLIMIT 1",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Outdated Images Across All Clusters",
   "type": "gauge",
   "description": "This panel displays the total count of outdated images from all cluster.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*)\n\nFROM default.outdated_images\n\nWHERE $timeFilterByColumn(EventTime) AND VersionsBehind > 0",
     "rawQuery": "SELECT count(*)\n\nFROM default.outdated_images\n\nWHERE EventTime >= toDateTime(1695283225) AND EventTime <= toDateTime(1695369625) AND VersionsBehind > 0",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Events across all Clusters",
   "type": "gauge",
   "description": "This panel displays the total number of events from all cluster.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) ",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693460292) AND EventTime <= toDateTime(1693460592)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of DeletedAPIs across all Clusters",
   "type": "gauge",
   "description": "This panel displays the total number of DeletedAPIs from all the cluster.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.DeletedAPIs\nWHERE $timeFilterByColumn(EventTime)",
     "rawQuery": "SELECT count(*) FROM default.DeletedAPIs\nWHERE EventTime >= toDateTime(1695367863) AND EventTime <= toDateTime(1695369663)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of DeprecatedAPIs across all Clusters",
   "type": "gauge",
   "description": "This panel displays the total count of DeprecatedAPIs in all cluster.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.DeprecatedAPIs\nWHERE $timeFilterByColumn(EventTime)",
     "rawQuery": "SELECT count(*) FROM default.DeprecatedAPIs\nWHERE EventTime >= toDateTime(1695367882) AND EventTime <= toDateTime(1695369682)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of k8s_Resources across all Clusters",
   "type": "gauge",
   "description": "Thos panel displays the total count of resources running in all kubernetes cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.getall_resources\nWHERE $timeFilterByColumn(EventTime)",
     "rawQuery": "SELECT count(*) FROM default.getall_resources\nWHERE EventTime >= toDateTime(1695367909) AND EventTime <= toDateTime(1695369709)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Pods over time",
   "type": "timeseries",
   "description": "This panel provides a time-based analysis of the occurrences of 'Pod'",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT EventTime, COUNT(*) AS Pods\nFROM default.events\nWHERE Kind = 'Pod'\nGROUP BY EventTime;\n"
    }
   ]
  },
  {
   "title": "Number of Nodes over Time",
   "type": "timeseries",
   "description": "This panel provides a time-based analysis of the occurrences of 'Node'",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT EventTime, COUNT(*) AS Nodes\nFROM default.events\nWHERE Kind = 'Node'\nGROUP BY EventTime;\n"
    }
   ]
  },
  {
   "title": "Number of Pod creation events",
   "type": "stat",
   "description": "This panel displays the total count events related to Pod.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Pod'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693438853) AND EventTime <= toDateTime(1693460453) AND Kind IN 'Pod'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of pods with Created state",
   "type": "gauge",
   "description": "This panel displays the total number of pods with Created state.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Pod' AND Reason IN 'Created'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693460172) AND EventTime <= toDateTime(1693460472) AND Kind IN 'Pod' AND Reason IN 'Created'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of pods with BackOff state",
   "type": "gauge",
   "description": "This panel displays the total number of pods with backOff state.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Pod' AND Reason IN 'BackOff'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693460182) AND EventTime <= toDateTime(1693460482) AND Kind IN 'Pod' AND Reason IN 'BackOff'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of pods with Unhealthy state",
   "type": "gauge",
   "description": "This panel displays the total number of pods with Unhealthy state.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Pod' AND Reason IN 'Unhealthy'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693460193) AND EventTime <= toDateTime(1693460493) AND Kind IN 'Pod' AND Reason IN 'Unhealthy'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Node creation events",
   "type": "stat",
   "description": "This panel displays the total count events related to node.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Node'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693438754) AND EventTime <= toDateTime(1693460354) AND Kind IN 'Node'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Nodes with NotReady State",
   "type": "gauge",
   "description": "This panel displays the total number of nodes which is in not ready state",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Node' AND Reason IN 'NodeNotReady'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693438784) AND EventTime <= toDateTime(1693460384) AND Kind IN 'Node' AND Reason IN 'NodeNotReady'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Nodes with Ready State",
   "type": "gauge",
   "description": "This panel displays the total number of nodes which is in ready state",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Node' AND Reason IN 'NodeReady'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693438825) AND EventTime <= toDateTime(1693460425) AND Kind IN 'Node' AND Reason IN 'NodeReady'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Nodes with  NodeHasNoDiskPressure State",
   "type": "gauge",
   "description": "This panel displays the total number of nodes which is in NodeHasNoDiskPressure state",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(*) FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Node' AND Reason IN 'NodeHasNoDiskPressure'",
     "rawQuery": "SELECT count(*) FROM default.events\nWHERE EventTime >= toDateTime(1693438835) AND EventTime <= toDateTime(1693460435) AND Kind IN 'Node' AND Reason IN 'NodeHasNoDiskPressure'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Events per cluster by Namespace",
   "type": "table",
   "description": "This panel displays the total number of events per cluster seperated by namespace.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName, Namespace, count(Event) AS Events FROM default.events\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY ClusterName,Namespace\nORDER BY Events DESC",
     "rawQuery": "SELECT ClusterName, Namespace, count(Event) AS Events FROM default.events\nWHERE EventTime >= toDateTime(1693460424) AND EventTime <= toDateTime(1693460724)\nGROUP BY ClusterName,Namespace\nORDER BY Events DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Clusters Containing DeletedAPIs Activity",
   "type": "gauge",
   "description": "This panel displays the total number of clusters containing DeletedAPIs activity.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT COUNT(DISTINCT ClusterName) AS DeletedAPIs\nFROM default.DeletedAPIs\nWHERE $timeFilterByColumn(EventTime)",
     "rawQuery": "SELECT COUNT(DISTINCT ClusterName) AS DeletedAPIs\nFROM default.DeletedAPIs\nWHERE EventTime >= toDateTime(1695369491) AND EventTime <= toDateTime(1695369791)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Clusters Containing Outdated Images Activity",
   "type": "gauge",
   "description": "This panel displays the total number of clusters containing Outdated Images activity.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(DISTINCT(ClusterName)) AS OutdatedImages\nFROM default.outdated_images\nWHERE $timeFilterByColumn(EventTime)",
     "rawQuery": "SELECT count(DISTINCT(ClusterName)) AS OutdatedImages\nFROM default.outdated_images\nWHERE EventTime >= toDateTime(1695369518) AND EventTime <= toDateTime(1695369818)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Clusters Containing DeprecatedAPIs Activity",
   "type": "gauge",
   "description": "This panel displays the total number of clusters containing DeprecatedAPIs activity.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT COUNT(DISTINCT ClusterName) AS DeprecatedAPIs\nFROM default.DeprecatedAPIs\nWHERE $timeFilterByColumn(EventTime)",
     "rawQuery": "SELECT COUNT(DISTINCT ClusterName) AS DeprecatedAPIs\nFROM default.DeprecatedAPIs\nWHERE EventTime >= toDateTime(1695369535) AND EventTime <= toDateTime(1695369835)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count of Pods grouped by Reason",
   "type": "table",
   "description": "This panel displays the total count of pods grouped by reason.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName, Reason, count(Kind) AS Pods FROM default.events\nWHERE $timeFilterByColumn(EventTime) AND Kind IN 'Pod' \nGROUP BY ClusterName,Reason",
     "rawQuery": "SELECT ClusterName, Reason, count(Kind) AS Pods FROM default.events\nWHERE EventTime >= toDateTime(1695369559) AND EventTime <= toDateTime(1695369859) AND Kind IN 'Pod' \nGROUP BY ClusterName,Reason",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count of DeprecatedAPIs per cluster",
   "type": "barchart",
   "description": "This panel displays the total count of DeprecatedAPIs for each clusters respectively.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName, count(Deprecated) AS DeprecatedAPIs FROM default.DeprecatedAPIs\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY ClusterName",
     "rawQuery": "SELECT ClusterName, count(Deprecated) AS DeprecatedAPIs FROM default.DeprecatedAPIs\nWHERE EventTime >= toDateTime(1695369580) AND EventTime <= toDateTime(1695369880)\nGROUP BY ClusterName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count of DeletedAPIs per cluster",
   "type": "barchart",
   "description": "This panel displays the total count of DeletedAPIs form each clusters respectively.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName, count(Deleted) AS DeletedAPIs FROM default.DeletedAPIs\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY ClusterName",
     "rawQuery": "SELECT ClusterName, count(Deleted) AS DeletedAPIs FROM default.DeletedAPIs\nWHERE EventTime >= toDateTime(1695369607) AND EventTime <= toDateTime(1695369907)\nGROUP BY ClusterName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count of Outdated Images per cluster",
   "type": "barchart",
   "description": "This panel displays the total count of outdated images from each cluster respectively.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName, count(CurrentImage) AS Outdated_Images FROM default.outdated_images\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY ClusterName",
     "rawQuery": "SELECT ClusterName, count(CurrentImage) AS Outdated_Images FROM default.outdated_images\nWHERE EventTime >= toDateTime(1695369627) AND EventTime <= toDateTime(1695369927)\nGROUP BY ClusterName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count of Events per cluster",
   "type": "barchart",
   "description": "This panel displays the total count of Events for each cluster respectively",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select ClusterName,count(Id) AS Events from default.events\nWHERE $timeFilterByColumn(EventTime) \ngroup by ClusterName",
     "rawQuery": "select ClusterName,count(Id) AS Events from default.events\nWHERE EventTime >= toDateTime(1693460253) AND EventTime <= toDateTime(1693460553) \ngroup by ClusterName",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Count of Resources per cluster",
   "type": "barchart",
   "description": "This panel displays the total count of resources for each clusters respectively",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName, count(Resource) AS Resources FROM default.getall_resources\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY ClusterName",
     "rawQuery": "SELECT ClusterName, count(Resource) AS Resources FROM default.getall_resources\nWHERE EventTime >= toDateTime(1695369653) AND EventTime <= toDateTime(1695369953)\nGROUP BY ClusterName",
     "round": "0s"
    }
   ]
  },
  {
   "title": " Resources per Cluster by Kind",
   "type": "table",
   "description": "This panel displays the total number resources for each Clusters seperated by Kind.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ClusterName, Kind, count(Resource) AS Resources FROM default.getall_resources\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY ClusterName,Kind\nORDER BY Resources DESC",
     "rawQuery": "SELECT ClusterName, Kind, count(Resource) AS Resources FROM default.getall_resources\nWHERE EventTime >= toDateTime(1695369674) AND EventTime <= toDateTime(1695369974)\nGROUP BY ClusterName,Kind\nORDER BY Resources DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Kubernetes Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kubernetes Resources",
     "type": "table",
     "description": "This panel displays all the resources running in the kubernetes cluster.",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT * FROM default.getall_resources\nWHERE $timeFilterByColumn(EventTime)",
       "rawQuery": "SELECT * FROM default.getall_resources\nWHERE EventTime >= toDateTime(1695369699) AND EventTime <= toDateTime(1695369999)",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "Outdated Images",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Outdated Images",
     "type": "table",
     "description": "This panel displays all the out-of-date images from the cluster.",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 87 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT * FROM default.outdated_images\nWHERE $timeFilterByColumn(EventTime) AND VersionsBehind > 0",
       "rawQuery": "SELECT * FROM default.outdated_images\nWHERE EventTime >= toDateTime(1695369722) AND EventTime <= toDateTime(1695370022) AND VersionsBehind > 0",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "DeletedAPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DeletedAPIs",
     "type": "table",
     "description": "This panel displays all the DeletedAPIs from the cluster.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT * FROM default.DeletedAPIs\nWHERE $timeFilterByColumn(EventTime)",
       "rawQuery": "SELECT * FROM default.DeletedAPIs\nWHERE EventTime >= toDateTime(1695369749) AND EventTime <= toDateTime(1695370049)",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "DeprecatedAPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DeprecatedAPIs",
     "type": "table",
     "description": "This panel displays all the DeprecatedAPIs from the cluster.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT * FROM default.DeprecatedAPIs\nWHERE $timeFilterByColumn(EventTime)",
       "rawQuery": "SELECT * FROM default.DeprecatedAPIs\nWHERE EventTime >= toDateTime(1695369773) AND EventTime <= toDateTime(1695370073)",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}