{
 "title": "Trivy",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Vulnerability Severity Distribution",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT vul_severity, count(*) AS total_count\nFROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date)\nGROUP BY vul_severity",
     "rawQuery": "SELECT vul_severity, count(*) AS total_count\nFROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694438766) AND vul_last_modified_date <= toDateTime(1694611566)\nGROUP BY vul_severity",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Misconfiguration Severity Distribution",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT misconfig_severity, count(*) AS total_count\nFROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY misconfig_severity",
     "rawQuery": "SELECT misconfig_severity, count(*) AS total_count\nFROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694438912) AND EventTime <= toDateTime(1694611712)\nGROUP BY misconfig_severity",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Vulnerability Severity counts grouped by Cluster",
   "type": "bargauge",
   "description": "This panel illustrates the distribution of vulnerability severities across different clusters. It provides an overview of the count of vulnerabilities categorized by severity levels within each cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, vul_severity, count(*) \nFROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date)\nGROUP BY cluster_name, vul_severity",
     "rawQuery": "SELECT cluster_name, vul_severity, count(*) \nFROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694155614) AND vul_last_modified_date <= toDateTime(1694242014)\nGROUP BY cluster_name, vul_severity",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Misconfiguration Severity counts grouped by Cluster",
   "type": "bargauge",
   "description": "This panel illustrates the distribution of misconfiguration severities across different clusters. It provides an overview of the count of misconfigurations categorized by severity levels within each cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, misconfig_severity, count(*)\nFROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY cluster_name, misconfig_severity",
     "rawQuery": "SELECT cluster_name, misconfig_severity, count(*)\nFROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694156239) AND EventTime <= toDateTime(1694242639)\nGROUP BY cluster_name, misconfig_severity",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Vulnerability Count by Cluster",
   "type": "gauge",
   "description": "This panel displays the total number Vulnerabilities under each namespace",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, count(*) FROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date)\nGROUP BY cluster_name",
     "rawQuery": "SELECT cluster_name, count(*) FROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694155665) AND vul_last_modified_date <= toDateTime(1694242065)\nGROUP BY cluster_name",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Misconfiguration Count by Cluster",
   "type": "gauge",
   "description": "This panel displays the total of misconfigurations from each clusters.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, count(*) FROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY cluster_name",
     "rawQuery": "SELECT cluster_name, count(*) FROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694156266) AND EventTime <= toDateTime(1694242666)\nGROUP BY cluster_name",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High Vulnerability Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of high vulnerabilities categorized by namespace. It helps to monitor and prioritize high security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(vul_severity) AS High_Severity\nFROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date) AND vul_severity = 'HIGH'\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(vul_severity) AS High_Severity\nFROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694155706) AND vul_last_modified_date <= toDateTime(1694242106) AND vul_severity = 'HIGH'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High Misconfiguration Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of high misconfigurations categorized by namespace. It helps to monitor and prioritize high security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(misconfig_severity) AS High_Severity\nFROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime) AND misconfig_severity = 'HIGH'\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(misconfig_severity) AS High_Severity\nFROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694156303) AND EventTime <= toDateTime(1694242703) AND misconfig_severity = 'HIGH'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Low Vulnerability Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of Low vulnerabilities categorized by namespace. It helps to monitor and prioritize Low security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(vul_severity) AS Low_Severity\nFROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date) AND vul_severity = 'LOW'\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(vul_severity) AS Low_Severity\nFROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694155745) AND vul_last_modified_date <= toDateTime(1694242145) AND vul_severity = 'LOW'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Low Misconfiguration Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of low misconfigurations categorized by namespace. It helps to monitor and prioritize low security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(misconfig_severity) AS Low_Severity\nFROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime) AND misconfig_severity = 'LOW'\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(misconfig_severity) AS Low_Severity\nFROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694156331) AND EventTime <= toDateTime(1694242731) AND misconfig_severity = 'LOW'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Medium Vulnerability Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of Medium vulnerabilities categorized by namespace. It helps to monitor and prioritize Medium security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(vul_severity) AS Medium_Severity\nFROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date) AND vul_severity = 'MEDIUM'\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(vul_severity) AS Medium_Severity\nFROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694155776) AND vul_last_modified_date <= toDateTime(1694242176) AND vul_severity = 'MEDIUM'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Medium  Misconfiguration Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of medium misconfigurations categorized by namespace. It helps to monitor and prioritize medium security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(misconfig_severity) AS Medium_Severity\nFROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime) AND misconfig_severity = 'MEDIUM'\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(misconfig_severity) AS Medium_Severity\nFROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694156357) AND EventTime <= toDateTime(1694242757) AND misconfig_severity = 'MEDIUM'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Critical Vulnerability Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of critical vulnerabilities categorized by namespace. It helps to monitor and prioritize critical security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(vul_severity) AS Critical_Severity\nFROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date) AND vul_severity = 'CRITICAL'\nGROUP BY cluster_name, namespace\n",
     "rawQuery": "SELECT cluster_name, namespace, count(vul_severity) AS Critical_Severity\nFROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694156016) AND vul_last_modified_date <= toDateTime(1694242416) AND vul_severity = 'CRITICAL'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Critical  Misconfiguration Count by Namespace and ClusterName",
   "type": "bargauge",
   "description": "This panel provides a count of critical misconfigurations categorized by namespace. It helps to monitor and prioritize critical security issues across different namespaces.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(misconfig_severity) AS Critical_Severity\nFROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime) AND misconfig_severity = 'CRITICAL'\nGROUP BY cluster_name, namespace\n",
     "rawQuery": "SELECT cluster_name, namespace, count(misconfig_severity) AS Critical_Severity\nFROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694156383) AND EventTime <= toDateTime(1694242783) AND misconfig_severity = 'CRITICAL'\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Vulnerability Count by Cluster and Namespace",
   "type": "bargauge",
   "description": "This panel displays the count of vulnerabilities in different clusters and namespaces.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(*) AS Vulnerabilities\nFROM default.trivy_vul\nWHERE $timeFilterByColumn(vul_last_modified_date)\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(*) AS Vulnerabilities\nFROM default.trivy_vul\nWHERE vul_last_modified_date >= toDateTime(1694156175) AND vul_last_modified_date <= toDateTime(1694242575)\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Misconfiguration Count by Cluster and Namespace",
   "type": "bargauge",
   "description": "This panel displays the count of Misconfigurations in different clusters and namespaces.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT cluster_name, namespace, count(*) AS Misconfigurations\nFROM default.trivy_misconfig\nWHERE $timeFilterByColumn(EventTime)\nGROUP BY cluster_name, namespace",
     "rawQuery": "SELECT cluster_name, namespace, count(*) AS Misconfigurations\nFROM default.trivy_misconfig\nWHERE EventTime >= toDateTime(1694156545) AND EventTime <= toDateTime(1694242945)\nGROUP BY cluster_name, namespace",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Trivy Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \"cluster_name\", \"namespace\", \"kind\", \"name\", \"vul_id\", \"vul_vendor_ids\", \"vul_pkg_id\", \"vul_pkg_name\", \"vul_pkg_path\", \"vul_installed_version\", \"vul_fixed_version\", \"vul_title\", \"vul_severity\", \"vul_published_date\", \"vul_last_modified_date\" \nFROM \"default\".\"trivy_vul\"\nWHERE $timeFilterByColumn(vul_last_modified_date)\nORDER BY vul_last_modified_date DESC",
     "rawQuery": "SELECT \"cluster_name\", \"namespace\", \"kind\", \"name\", \"vul_id\", \"vul_vendor_ids\", \"vul_pkg_id\", \"vul_pkg_name\", \"vul_pkg_path\", \"vul_installed_version\", \"vul_fixed_version\", \"vul_title\", \"vul_severity\", \"vul_published_date\", \"vul_last_modified_date\" \nFROM \"default\".\"trivy_vul\"\nWHERE vul_last_modified_date >= toDateTime(1694099993) AND vul_last_modified_date <= toDateTime(1694186393)\nORDER BY vul_last_modified_date DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Trivy Misconfiguration",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \"cluster_name\", \"EventTime\", \"namespace\", \"kind\", \"name\", \"misconfig_id\", \"misconfig_avdid\", \"misconfig_type\", \"misconfig_title\", \"misconfig_desc\", \"misconfig_msg\", \"misconfig_query\", \"misconfig_resolution\", \"misconfig_severity\", \"misconfig_status\" \nFROM \"default\".\"trivy_misconfig\"\nWHERE $timeFilterByColumn(EventTime)\nORDER BY EventTime DESC",
     "rawQuery": "SELECT \"cluster_name\", \"EventTime\", \"namespace\", \"kind\", \"name\", \"misconfig_id\", \"misconfig_avdid\", \"misconfig_type\", \"misconfig_title\", \"misconfig_desc\", \"misconfig_msg\", \"misconfig_query\", \"misconfig_resolution\", \"misconfig_severity\", \"misconfig_status\" \nFROM \"default\".\"trivy_misconfig\"\nWHERE EventTime >= toDateTime(1694966455) AND EventTime <= toDateTime(1695052855)\nORDER BY EventTime DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Trivy Image",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \"cluster_name\", \"artifact_name\", \"vul_id\", \"vul_pkg_id\", \"vul_pkg_name\", \"vul_installed_version\", \"vul_fixed_version\", \"vul_title\", \"vul_severity\", \"vul_published_date\", \"vul_last_modified_date\" \nFROM \"default\".\"trivyimage\"\nWHERE $timeFilterByColumn(vul_last_modified_date)\nORDER BY vul_last_modified_date DESC",
     "rawQuery": "SELECT \"cluster_name\", \"artifact_name\", \"vul_id\", \"vul_pkg_id\", \"vul_pkg_name\", \"vul_installed_version\", \"vul_fixed_version\", \"vul_title\", \"vul_severity\", \"vul_published_date\", \"vul_last_modified_date\" \nFROM \"default\".\"trivyimage\"\nWHERE vul_last_modified_date >= toDateTime(1693581675) AND vul_last_modified_date <= toDateTime(1694186475)\nORDER BY vul_last_modified_date DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Trivy_SBOM",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \"schema\", \"bom_format\", \"spec_version\", \"serial_number\", \"version\", \"metadata_timestamp\", \"metatool_vendor\", \"metatool_name\", \"metatool_version\", \"component_bom_ref\", \"component_type\", \"component_name\", \"component_version\", \"component_property_name\", \"component_property_value\", \"component_hash_alg\", \"component_hash_content\", \"component_license_exp\", \"component_purl\", \"dependency_ref\" \nFROM \"default\".\"trivysbom\"\nWHERE $timeFilterByColumn(metadata_timestamp)\nORDER BY metadata_timestamp DESC",
     "rawQuery": "SELECT \"schema\", \"bom_format\", \"spec_version\", \"serial_number\", \"version\", \"metadata_timestamp\", \"metatool_vendor\", \"metatool_name\", \"metatool_version\", \"component_bom_ref\", \"component_type\", \"component_name\", \"component_version\", \"component_property_name\", \"component_property_value\", \"component_hash_alg\", \"component_hash_content\", \"component_license_exp\", \"component_purl\", \"dependency_ref\" \nFROM \"default\".\"trivysbom\"\nWHERE metadata_timestamp >= toDateTime(1693581733) AND metadata_timestamp <= toDateTime(1694186533)\nORDER BY metadata_timestamp DESC",
     "round": "0s"
    }
   ]
  }
 ]
}