{
 "title": "kubedatas",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "SELECT namespace FROM default.events"
   },
   {
    "name": "reason",
    "query": "SELECT reason FROM default.events"
   },
   {
    "name": "kind",
    "query": "SELECT kind FROM default.events"
   }
  ]
 },
 "panels": [
  {
   "title": "healthy pods in Namespace : $namespace",
   "type": "stat",
   "description": "This stats panel shows the healthy pods ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count()\nFROM $table\n\nWHERE reason IN ('Healthy') AND namespace IN ($namespace)\n\n",
     "rawQuery": "SELECT\n    count()\nFROM default.events\n\nWHERE reason IN ('Healthy') AND namespace IN ('default','kubviz')",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "unHealthy  pods in Namespace: $namespace",
   "type": "stat",
   "description": "This stats panel shows the unhealthy pods ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    count()\nFROM $table\n\nWHERE reason IN ('Unhealthy') AND namespace IN ($namespace)\n\n\n\n\n",
     "rawQuery": "SELECT\n    count()\nFROM default.events\n\nWHERE reason IN ('Unhealthy') AND namespace IN ('default','kubviz')",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "kubernetes",
   "type": "table",
   "description": "This table panal shows all the kubernetes datas.\nif its not showing the data check the time range and refresh.it will take some time to load the data. wait for sometime before clicking refresh another time.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT *\r\n    \r\nFROM $table\r\n\r\nWHERE namespace IN ($namespace) AND reason IN ($reason) AND $timeFilter AND kind IN ($kind)\r\n",
     "rawQuery": "SELECT *\r\n    \r\nFROM default.events\r\n\r\nWHERE namespace IN ('kube-system','kubviz','default','monitoring','argocd','istio-system','crossplane-system','ingress-system','tekton-pipelines','kyverno') AND reason IN ('ApplyingManifest','ApplyManifestFailed','SuccessfulCreate','FailedScheduling','Starting','InvalidDiskCapacity','NodeHasSufficientMemory','NodeHasNoDiskPressure','NodeHasSufficientPID','NodeAllocatableEnforced','Scheduled','RegisteredNode','Pulling','Pulled','Created','Started','NodeReady','FailedToUpdateEndpoint','NoPods','RemovingNode','LeaderElection','EnsuringLoadBalancer','EnsuredLoadBalancer','Synced','FailedToUpdateEndpointSlices','Updated','Unhealthy','ApplyRoles','TaintManagerEviction','FailedCreate','FailedMount','BackOff','ResourceUpdated','UpdatedLoadBalancer','FailedGetResourceMetric','Killing','FailedKillPod','UnpackPackage') AND event_time >= toDateTime(1650613877) AND event_time <= toDateTime(1650635477) AND kind IN ('Addon','ReplicaSet','Pod','Node','DaemonSet','Endpoints','PodDisruptionBudget','Lease','Service','Secret','ConfigMap','Namespace','StatefulSet','Application','HorizontalPodAutoscaler','Provider')",
     "round": "0s",
     "table": "events"
    }
   ]
  }
 ]
}