{
 "title": "Kubviz Features",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes Resources",
   "type": "table",
   "description": "This panel displays all the resources from the cluster.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.getall_resources",
     "rawQuery": "SELECT * FROM default.getall_resources",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Outdated Images",
   "type": "table",
   "description": "This panel displays all the out-of-date images from the cluster.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.outdated_images\nWHERE VersionsBehind > 0",
     "rawQuery": "SELECT * FROM default.outdated_images\nWHERE VersionsBehind > 0",
     "round": "0s"
    }
   ]
  },
  {
   "title": "DeletedAPIs",
   "type": "table",
   "description": "This panel displays all the DeletedAPIs from the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.DeletedAPIs",
     "rawQuery": "SELECT * FROM default.DeletedAPIs",
     "round": "0s"
    }
   ]
  },
  {
   "title": "DeprecatedAPIs",
   "type": "table",
   "description": "This panel displays all the DeprecatedAPIs from the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM default.DeprecatedAPIs",
     "rawQuery": "SELECT * FROM default.DeprecatedAPIs",
     "round": "0s"
    }
   ]
  }
 ]
}