{
 "title": "kubviz_plugins",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kubernetes_resources",
   "type": "table",
   "description": "This panel displays all the resources in the kubernetes cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from default.getall_resources",
     "rawQuery": "select * from default.getall_resources",
     "round": "0s"
    }
   ]
  },
  {
   "title": "outdated_images",
   "type": "table",
   "description": "This panel will displays all the out-of-date images running in a Kubernetes cluster.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from default.outdated_images",
     "rawQuery": "select * from default.outdated_images",
     "round": "0s"
    }
   ]
  },
  {
   "title": "deprecated_and_deletedAPIs",
   "type": "table",
   "description": "This panel displays all the deprecated and deleted APIs in the kubernetes cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from default.deprecatedAPIs_and_deletedAPIs",
     "rawQuery": "select * from default.deprecatedAPIs_and_deletedAPIs",
     "round": "0s"
    }
   ]
  }
 ]
}