// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List of APIs provided by the service
	// (GET /api-docs)
	GetApiDocs(c *gin.Context)
	// Post Azure Container Registry webhook events
	// (POST /event/azure/container)
	PostEventAzureContainer(c *gin.Context)
	// Post Dockerhub artifactory events
	// (POST /event/docker/hub)
	PostEventDockerHub(c *gin.Context)
	// Post Jfrog Container Registry webhook events
	// (POST /event/jfrog/container)
	PostEventJfrogContainer(c *gin.Context)
	// Kubernetes readiness and liveness probe endpoint
	// (GET /status)
	GetStatus(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiDocs operation middleware
func (siw *ServerInterfaceWrapper) GetApiDocs(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetApiDocs(c)
}

// PostEventAzureContainer operation middleware
func (siw *ServerInterfaceWrapper) PostEventAzureContainer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostEventAzureContainer(c)
}

// PostEventDockerHub operation middleware
func (siw *ServerInterfaceWrapper) PostEventDockerHub(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostEventDockerHub(c)
}

// PostEventJfrogContainer operation middleware
func (siw *ServerInterfaceWrapper) PostEventJfrogContainer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostEventJfrogContainer(c)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetStatus(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api-docs", wrapper.GetApiDocs)

	router.POST(options.BaseURL+"/event/azure/container", wrapper.PostEventAzureContainer)

	router.POST(options.BaseURL+"/event/docker/hub", wrapper.PostEventDockerHub)

	router.POST(options.BaseURL+"/event/jfrog/container", wrapper.PostEventJfrogContainer)

	router.GET(options.BaseURL+"/status", wrapper.GetStatus)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6yTQW/TQBCF/8pqziZO4eZbRCsoRWrVcKt6WK/HyVBnZzUzaxQi/3e0jiiooBIKJ2uk",
	"995882wfIPAuccRoCs1hqoBiz9AcoEMNQsmIIzTwlqN5iiiuFeo26K4TRnd7sf7kVjeXThMG6in4WV6B",
	"kQ34Z9v6iW1E0eO+s8VysYSpAk4YfSJo4M1iuTiDCpK3bWGF2id61XGYhw1aeXBCmdMuO2jgHdoq0XmR",
	"VCCoiaPiLH+9XP565PUVTFMFmnc7L3to4COpOe4Lq7okPFKHnWv3zrboFGWkgOVav1Fo7iDldqAA9yWk",
	"xhGj1f5rFqzD9xrKzsT6G9QbVrsollVxPPb2Mu4S5uYg9+MN3OKG1GTvvmC7ZX5wM6E+z99xeECpt7k9",
	"Af18Fr/P7T9QHzO2uXVejHofjGV/EurnXnjzV1V/KI7/UfUc9PKq1bzlZ7/i9VFxCqHmEFC1z4N7jHnC",
	"fJVblIiG6gR9RxFVnY+dG2jEeUjCLTqMXWKK9jO30OgNC3iJRCm/LDR3B8gyQAM1TPfTtwAAAP//tJ+y",
	"/VUEAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
