
name: ci
on:
  push:
    branches:
      - "*"
      - main
  pull_request:

permissions:
  contents: write
  security-events: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -coverpkg=./... -covermode=atomic
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: -v --config=.ci.yml
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Static check
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.6"
          install-go: false
          cache-key: '1.21'
